"""Add cpm and wpm columns to User model

Revision ID: 1155f8ce17aa
Revises: 2d218f4d7ddd
Create Date: 2026-01-11 18:02:09.766810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1155f8ce17aa'
down_revision = '2d218f4d7ddd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['text_id'], ['typing_texts.id'], name=op.f('fk_favorites_text_id_typing_texts')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_favorites_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'text_id', name=op.f('pk_favorites'))
    )
    with op.batch_alter_table('typing_results', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_typing_results_text_id_typing_texts'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_typing_results_text_id_typing_texts'), 'typing_texts', ['text_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('best_cpm', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('avg_cpm', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('best_wpm', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('avg_wpm', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('ranking_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')
        batch_op.drop_column('ranking_score')
        batch_op.drop_column('avg_wpm')
        batch_op.drop_column('best_wpm')
        batch_op.drop_column('avg_cpm')
        batch_op.drop_column('best_cpm')

    with op.batch_alter_table('typing_results', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_typing_results_text_id_typing_texts'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_typing_results_text_id_typing_texts'), 'typing_texts', ['text_id'], ['id'])

    op.drop_table('favorites')
    # ### end Alembic commands ###
