"""add ranking_score to user

Revision ID: 1c194d9ad6ad
Revises: 
Create Date: 2026-01-24 13:39:17.160129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c194d9ad6ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_performances', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_api_performances_report_id_test_reports'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_api_performances_report_id_test_reports'), 'test_reports', ['report_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_favorites_text_id_typing_texts'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_favorites_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_favorites_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_favorites_text_id_typing_texts'), 'typing_texts', ['text_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('test_case_results', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_test_case_results_report_id_test_reports'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_test_case_results_report_id_test_reports'), 'test_reports', ['report_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('ranking_score',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('ranking_score',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('test_case_results', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_test_case_results_report_id_test_reports'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_test_case_results_report_id_test_reports'), 'test_reports', ['report_id'], ['id'])

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_favorites_text_id_typing_texts'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_favorites_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_favorites_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_favorites_text_id_typing_texts'), 'typing_texts', ['text_id'], ['id'])

    with op.batch_alter_table('api_performances', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_api_performances_report_id_test_reports'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_api_performances_report_id_test_reports'), 'test_reports', ['report_id'], ['id'])

    # ### end Alembic commands ###
