"""Add image_url to TypingText

Revision ID: 5211a237ad4d
Revises: c54078bba1ba
Create Date: 2025-12-28 20:37:19.970980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5211a237ad4d'
down_revision = 'c54078bba1ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('typing_texts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('typing_texts', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
