"""Reset and integrate reports

Revision ID: 9494a18e52b9
Revises: 
Create Date: 2026-01-18 15:22:17.348506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9494a18e52b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_test_reports')
    with op.batch_alter_table('test_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('git_commit', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('user_count', sa.Integer(), nullable=True))

    with op.batch_alter_table('typing_results', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_typing_results_text_id_typing_texts'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_typing_results_text_id_typing_texts'), 'typing_texts', ['text_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('best_cpm', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('avg_cpm', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('best_wpm', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('avg_wpm', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('ranking_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')
        batch_op.drop_column('ranking_score')
        batch_op.drop_column('avg_wpm')
        batch_op.drop_column('best_wpm')
        batch_op.drop_column('avg_cpm')
        batch_op.drop_column('best_cpm')

    with op.batch_alter_table('typing_results', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_typing_results_text_id_typing_texts'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_typing_results_text_id_typing_texts'), 'typing_texts', ['text_id'], ['id'])

    with op.batch_alter_table('test_reports', schema=None) as batch_op:
        batch_op.drop_column('user_count')
        batch_op.drop_column('git_commit')

    op.create_table('_alembic_tmp_test_reports',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('test_time', sa.DATETIME(), nullable=True),
    sa.Column('total_tests', sa.INTEGER(), nullable=True),
    sa.Column('is_passed', sa.BOOLEAN(), nullable=True),
    sa.Column('git_commit', sa.VARCHAR(length=40), nullable=True),
    sa.Column('user_count', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_test_reports'))
    )
    # ### end Alembic commands ###
