"""add performance latency fields

Revision ID: 9c71ac4855b1
Revises: 1c194d9ad6ad
Create Date: 2026-01-24 16:20:01.702839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c71ac4855b1'
down_revision = '1c194d9ad6ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_performances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('p95_latency', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('p99_latency', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('max_latency', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_requests', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('error_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('is_satisfied', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_performances', schema=None) as batch_op:
        batch_op.drop_column('is_satisfied')
        batch_op.drop_column('error_rate')
        batch_op.drop_column('total_requests')
        batch_op.drop_column('max_latency')
        batch_op.drop_column('p99_latency')
        batch_op.drop_column('p95_latency')

    # ### end Alembic commands ###
